// {PATH_TO_PROJECT}/src/prompt/examAnalysisPrompt.js

/**
 * Generates the original, simple prompt for analyzing a multilevel speaking exam.
 * @param {string} formattedTranscript - The user's transcript.
 * @param {object} partConfig - The configuration object for exam parts (partAnalysisConfig).
 * @param {boolean} isSinglePartPractice - True if analyzing a single part.
 * @param {string|null} practicePart - The key for the specific part being practiced.
 * @returns {string} The complete prompt for the simple AI analysis.
 */
export const generateSimpleAnalysisPrompt = (
  formattedTranscript,
  partConfig,
  isSinglePartPractice,
  practicePart
) => {
  const sttAwarenessPrompt = `
    CONTEXT: The following transcript was generated by an automated speech-to-text (STT) engine. The user is a non-native English speaker from Uzbekistan. Your primary task is to assess the user's spoken English ability, NOT the quality of the transcription.
    
    THEREFORE, YOU MUST:
    1. Infer the user's intended meaning. Be lenient with spelling, grammatical errors, or awkward phrasing that are likely STT artifacts (e.g., misheard words, homophones like 'their' vs 'there').
    2. Base your assessment on the substance of the response: vocabulary range, sentence structure complexity, coherence, and relevance to the question.
    3. If a portion of the transcript is completely nonsensical, acknowledge it as a likely STT failure and evaluate the parts of the response that are clear.
    `;

  if (isSinglePartPractice && partConfig[practicePart]) {
    const config = partConfig[practicePart];
    return `
            You are an expert examiner for a structured, multilevel English speaking test.
            The user is practicing a single part of the exam: ${config.partName}. The maximum score for this part is ${config.maxScore}.
            ${sttAwarenessPrompt}
            Analyze the following speaking test transcript.
            TRANSCRIPT:\n---\n${formattedTranscript}\n---\n
            CRITICAL: Your entire response must be ONLY a single, valid JSON object using this exact structure, with no extra text or explanations.
            { "part": "${config.partName}", "score": <number>, "feedback": "${config.promptFocus}" }`;
  } else {
    return `
            You are an expert examiner for a structured, multilevel English speaking test. The maximum score is 72.
            ${sttAwarenessPrompt}
            The exam has 4 parts:
            - Part 1.1: 3 personal questions (${partConfig.P1_1.maxScore} points total)
            - Part 1.2: Picture comparison (${partConfig.P1_2.maxScore} points total)
            - Part 2: Single picture monologue (${partConfig.P2.maxScore} points total)
            - Part 3: Argumentative monologue (${partConfig.P3.maxScore} points total)
            Based on the transcript, provide a score and constructive feedback for each part. Calculate the final total score (out of 72).
            TRANSCRIPT:\n---\n${formattedTranscript}\n---\n
            CRITICAL: Your entire response must be ONLY a single, valid JSON object using this exact structure, with no extra text or explanations.
            { "totalScore": <number>, "feedbackBreakdown": [
              { "part": "Part 1.1", "score": <number>, "feedback": "${partConfig.P1_1.promptFocus}" },
              { "part": "Part 1.2", "score": <number>, "feedback": "${partConfig.P1_2.promptFocus}" },
              { "part": "Part 2", "score": <number>, "feedback": "${partConfig.P2.promptFocus}" },
              { "part": "Part 3", "score": <number>, "feedback": "${partConfig.P3.promptFocus}" }
            ]}`;
  }
};

/**
 * Generates a detailed, localized prompt for analyzing a multilevel speaking exam.
 * @param {string} formattedTranscript - The user's transcript, pre-formatted as a single string.
 * @param {object} partConfig - The configuration object for exam parts (e.g., partAnalysisConfig).
 * @param {boolean} isSinglePartPractice - True if analyzing a single part, false for a full exam.
 * @param {string|null} practicePart - The key for the specific part being practiced (e.g., "P1_2").
 * @param {string} targetLanguage - The ISO 639-1 code for the desired feedback language (e.g., 'uz').
 * @returns {string} The complete prompt for the AI model.
 */
export const generateDetailedAnalysisPrompt = (
  formattedTranscript,
  partConfig,
  isSinglePartPractice,
  practicePart,
  targetLanguage = "en"
) => {
  // Map of ISO codes to full language names for clearer AI instructions.
  const languageMap = {
    en: "English",
    uz: "Uzbek",
    ru: "Russian",
    es: "Spanish",
    // Add other supported languages here
  };
  const languageName = languageMap[targetLanguage] || "English";

  // This instruction block is added to the prompt only if a non-English language is requested.
  const localizationInstruction =
    targetLanguage && targetLanguage !== "en"
      ? `
        CRITICAL LANGUAGE REQUIREMENT: All human-readable feedback text within the JSON response (specifically the values for "overallFeedback", "positive", "suggestion", and the "improved version" part of "example") MUST be written in ${languageName} (language code: ${targetLanguage}).
        - DO NOT translate the JSON keys (like "part", "score", "detailedBreakdown"). They must remain in English.
        - The user's original quote in the "example" field should remain in English.
        - The example for the "example" field should follow this format: "You said: '[user's quote in English]'. A better way to say this in ${languageName} is: '[your suggested improvement in the target language]'."
        `
      : "";

  // General instructions that apply to all analyses.
  const sttAwarenessPrompt = `
    CONTEXT: The following transcript was generated by an automated speech-to-text (STT) engine. The user is a non-native English speaker. Your primary task is to assess the user's spoken English ability, NOT the quality of the transcription.
    THEREFORE, YOU MUST:
    1. Infer the user's intended meaning. Be lenient with spelling, grammatical errors, or awkward phrasing that are likely STT artifacts.
    2. Base your assessment on the substance of the response: vocabulary range, sentence structure complexity, coherence, and relevance to the question.
    3. If a portion of the transcript is nonsensical, acknowledge it as a likely STT failure and evaluate the parts that are clear.`;

  const detailedFeedbackInstructions = `
    For each part of the exam, provide a detailed breakdown of the user's performance across four categories:
    1.  **Fluency and Coherence:** Assess flow, hesitations, and logical connection of ideas.
    2.  **Lexical Resource (Vocabulary):** Evaluate the range and precision of vocabulary.
    3.  **Grammatical Range and Accuracy:** Analyze sentence structures and grammatical correctness.
    4.  **Task Achievement:** Judge how well the user addressed the specific requirements of the question(s).

    For each category, you MUST provide:
    - "positive": A brief comment on what the user did well.
    - "suggestion": A constructive tip for improvement.
    - "example": A direct quote from the user's transcript illustrating your 'suggestion', followed by an improved version. If no specific example fits, just explain the suggestion.`;

  // Generate the final prompt based on whether it's for a single part or a full exam.
  if (isSinglePartPractice && partConfig[practicePart]) {
    const config = partConfig[practicePart];
    return `
            You are an expert examiner for a structured, multilevel English speaking test.
            The user is practicing a single part: ${config.partName}. The maximum score for this part is ${config.maxScore}.
            ${sttAwarenessPrompt}
            Analyze the following transcript.
            TRANSCRIPT:\n---\n${formattedTranscript}\n---\n
            ${detailedFeedbackInstructions}
            ${localizationInstruction}
            CRITICAL: Your entire response must be ONLY a single, valid JSON object using this exact structure, with no extra text or explanations.
            {
              "part": "${config.partName}",
              "score": <number out of ${config.maxScore}>,
              "overallFeedback": "<string, 1-2 sentences summarizing the performance for this part>",
              "detailedBreakdown": {
                "fluencyAndCoherence": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" },
                "lexicalResource": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" },
                "grammaticalRangeAndAccuracy": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" },
                "taskAchievement": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }
              }
            }`;
  } else {
    return `
            You are an expert examiner for a structured, multilevel English speaking test with a maximum score of 72.
            The exam has 4 parts with the following point distributions: Part 1.1 (${partConfig.P1_1.maxScore} pts), Part 1.2 (${partConfig.P1_2.maxScore} pts), Part 2 (${partConfig.P2.maxScore} pts), Part 3 (${partConfig.P3.maxScore} pts).
            ${sttAwarenessPrompt}
            Analyze the entire transcript.
            TRANSCRIPT:\n---\n${formattedTranscript}\n---\n
            ${detailedFeedbackInstructions}
            ${localizationInstruction}
            CRITICAL: Your entire response must be ONLY a single, valid JSON object using this exact structure, with no extra text or explanations.
            {
              "totalScore": <number, sum of part scores, max 72>,
              "feedbackBreakdown": [
                {
                  "part": "Part 1.1", "score": <number out of ${partConfig.P1_1.maxScore}>, "overallFeedback": "<string>",
                  "detailedBreakdown": { "fluencyAndCoherence": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "lexicalResource": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "grammaticalRangeAndAccuracy": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "taskAchievement": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" } }
                },
                {
                  "part": "Part 1.2", "score": <number out of ${partConfig.P1_2.maxScore}>, "overallFeedback": "<string>",
                  "detailedBreakdown": { "fluencyAndCoherence": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "lexicalResource": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "grammaticalRangeAndAccuracy": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "taskAchievement": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" } }
                },
                {
                  "part": "Part 2", "score": <number out of ${partConfig.P2.maxScore}>, "overallFeedback": "<string>",
                  "detailedBreakdown": { "fluencyAndCoherence": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "lexicalResource": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "grammaticalRangeAndAccuracy": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "taskAchievement": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" } }
                },
                {
                  "part": "Part 3", "score": <number out of ${partConfig.P3.maxScore}>, "overallFeedback": "<string>",
                  "detailedBreakdown": { "fluencyAndCoherence": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "lexicalResource": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "grammaticalRangeAndAccuracy": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" }, "taskAchievement": { "positive": "<string>", "suggestion": "<string>", "example": "<string>" } }
                }
              ]
            }`;
  }
};
